### ISSUE TITLE
Failed installation with PHP 8

### ISSUE THREAD

**Issue by Deepcodeinnovations** [AGILEDROP/laravel-telnyx#4]
It does not work with php 8. Please you need to update it to work with PHP 8

error details///

  Package agiledrop/laravel-telnyx has a PHP requirement incompatible with your PHP ve
  rsion, PHP extensions and Composer version:
    - agiledrop/laravel-telnyx 1.0.0 requires php ^7.4 which does not match your insta
  lled version 8.0.12.

**Comment by davide-casiraghi** [comment]
Should be fixed now with this.
https://github.com/AGILEDROP/laravel-telnyx/pull/5

**Comment by Deepcodeinnovations** [comment]
Okay, Let me try the installation again

**Comment by Deepcodeinnovations** [comment]
![sdfvsdvsdvsdvsdvc](https://user-images.githubusercontent.com/85382663/143459484-030b0960-8863-489d-9017-d341d7152edd.PNG)
